/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 04-may.-2022 6:45:35 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `FACTURAS` CASCADE
;

/* Create Tables */

CREATE TABLE `FACTURAS`
(
	`ID_FACTURA` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Código identificador de la factura. Es la llave primaria de la tabla.',
	`TIPO_DOCUMENTO_CLIENTE` INT UNSIGNED NOT NULL COMMENT 'Código identificador del tipo de documento de identificación del cliente. Es campo de llave foránea con la tabla PERSONAS.',
	`NUMERO_DOCUMENTO_CLIENTE` DECIMAL(15,0) NOT NULL COMMENT 'Número de identificación del cliente. Es campo de llave foránea con la tabla PERSONAS.',
	`TIPO_DOCUMENTO_MECANICO` INT UNSIGNED NOT NULL COMMENT 'Código identificador del tipo de documento de identificación del mecánico. Es campo de llave foránea con la tabla PERSONAS.',
	`NUMERO_DOCUMENTO_MECANICO` DECIMAL(15,0) NOT NULL COMMENT 'Número de identificación del mecánico. Es campo de llave foránea con la tabla PERSONAS.',
	`FECHA_FACTURA` DATE NOT NULL COMMENT 'Fecha de expedición de la factura.',
	`SUBTOTAL` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Valor parcial constituído por la suma de los repuestos y servicios detallados en la factura.',
	`VALOR_IVA` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Valor correspondiente al 19% del valor en SUBTOTAL.',
	`TOTAL_FACTURA` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Valor total de la factura, que corresponde a la suma de los valores en los campos SUBTOTAL y VALOR_IVA.',
	CONSTRAINT `PK_FACTURAS` PRIMARY KEY (`ID_FACTURA` ASC)
)
COMMENT = 'Tabla que almacena los datos generales de las facturas generadas.'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FACTURAS` 
 ADD INDEX `IDX_IDEN_CLIENTE` (`TIPO_DOCUMENTO_CLIENTE` ASC, `NUMERO_DOCUMENTO_CLIENTE` ASC)
;

ALTER TABLE `FACTURAS` 
 ADD INDEX `IDX_IDEN_MECANICO` (`TIPO_DOCUMENTO_MECANICO` ASC, `NUMERO_DOCUMENTO_MECANICO` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FACTURAS` 
 ADD CONSTRAINT `FK_FACTURAS_PERSONAS_CLI`
	FOREIGN KEY (`TIPO_DOCUMENTO_CLIENTE`, `NUMERO_DOCUMENTO_CLIENTE`) REFERENCES `PERSONAS` (`ID_TIPO_DOCUMENTO`,`NUMERO_DOCUMENTO`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `FACTURAS` 
 ADD CONSTRAINT `FK_FACTURAS_PERSONAS_MEC`
	FOREIGN KEY (`TIPO_DOCUMENTO_MECANICO`, `NUMERO_DOCUMENTO_MECANICO`) REFERENCES `PERSONAS` (`ID_TIPO_DOCUMENTO`,`NUMERO_DOCUMENTO`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
