/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 04-may.-2022 5:23:10 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `PRODUCTOS` CASCADE
;

/* Create Tables */

CREATE TABLE `PRODUCTOS`
(
	`ID_PRODUCTO` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Código identificador del producto, que puede ser un repuesto o un servicio. Es la llave primaria de la tabla.',
	`DESCRIPCION` NVARCHAR(200) NOT NULL COMMENT 'Descripción detallada del producto a ofrecer.',
	`CANTIDAD_EXISTENCIAS` DECIMAL(6,0) NOT NULL DEFAULT 0 COMMENT 'Número de unidades disponibles para la venta del producto a ofrecer.',
	`VALOR_UNITARIO_COMPRA` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Valor de compra de cada unidad del producto.',
	`VALOR_UNITARIO_VENTA` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Valor de venta establecido para cada unidad del producto.',
	`ID_TIPO_PRODUCTO` INT UNSIGNED NOT NULL COMMENT 'Código identificador del tipo de producto. Es campo de llave foránea con la tabla TIPOS_PRODUCTO.',
	CONSTRAINT `PK_PRODUCTOS` PRIMARY KEY (`ID_PRODUCTO` ASC)
)
COMMENT = 'Tabla donde se almacenan los datos de los repuestos y de los servicios ofrecidos.'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `PRODUCTOS` 
 ADD INDEX `IDX_TIPO_PRODUCTO` (`ID_TIPO_PRODUCTO` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `PRODUCTOS` 
 ADD CONSTRAINT `FK_PRODUCTOS_TIPOS_PRODUCTO`
	FOREIGN KEY (`ID_TIPO_PRODUCTO`) REFERENCES `TIPOS_PRODUCTO` (`ID_TIPO_PRODUCTO`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
