/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 05-may.-2022 4:46:02 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `VEHICULOS` CASCADE
;

/* Create Tables */

CREATE TABLE `VEHICULOS`
(
	`MATRICULA` NVARCHAR(10) NOT NULL COMMENT 'Placa o matrícula que identifica el vehículo.',
	`MARCA` NVARCHAR(30) NOT NULL COMMENT 'Marca del vehículo.',
	`REFERENCIA` VARCHAR(50) NOT NULL COMMENT 'Referencia del vehículo.',
	`MODELO` DECIMAL(4,0) NOT NULL COMMENT 'Año o modelo del vehículo.',
	`COLOR` NVARCHAR(30) NOT NULL COMMENT 'Color oficial del vehículo.',
	`TIPO_DOCUMENTO_CLIENTE` INT UNSIGNED NOT NULL COMMENT 'Tipo de documento de identificación del cliente dueño del vehículo. Es campo de llave foránea con la tabla PERSONAS.',
	`NUMERO_DOCUMENTO_CLIENTE` DECIMAL(15,0) NOT NULL COMMENT 'Número de documento de identificación del cliente dueño del vehículo. Es campo de llave foránea con la tabla PERSONAS.',
	CONSTRAINT `PK_VEHICULOS` PRIMARY KEY (`MATRICULA` ASC)
)
COMMENT = 'Tabla que almacena los datos de los vehículos atendidos.'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `VEHICULOS` 
 ADD INDEX `IDX_VEHICULOS_PERSONAS` (`TIPO_DOCUMENTO_CLIENTE` ASC, `NUMERO_DOCUMENTO_CLIENTE` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `VEHICULOS` 
 ADD CONSTRAINT `FK_VEHICULOS_PERSONAS`
	FOREIGN KEY (`TIPO_DOCUMENTO_CLIENTE`, `NUMERO_DOCUMENTO_CLIENTE`) REFERENCES `PERSONAS` (`ID_TIPO_DOCUMENTO`,`NUMERO_DOCUMENTO`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
