/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 04-may.-2022 5:24:15 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `DETALLE_FACTURAS` CASCADE
;

/* Create Tables */

CREATE TABLE `DETALLE_FACTURAS`
(
	`ID_DETALLE_FACTURA` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Código identificador del detalle. Es la llave primaria de la tabla.',
	`ID_PRODUCTO` INT UNSIGNED NOT NULL COMMENT 'Código identificador del elemento detallado en el registro. Puede ser un repuesto o un servicio. Es campo de llave foránea con la tabla PRODUCTOS.',
	`ID_FACTURA` INT UNSIGNED NOT NULL COMMENT 'Código identificador de la factura a la que pertenece este detalle.',
	`CANTIDAD` DECIMAL(6,0) NOT NULL DEFAULT 0 COMMENT 'Cantidad de repuestos o de servicios utilizados en este detalle.',
	`VALOR_PRODUCTO` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Valor correspondiente al producto del valor unitario de venta (de repuestos) o del valor de mano de obra (de servicios) y el dato en el campo CANTIDAD.',
	`VALOR_DESCUENTO` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Valor de descuento aplicado según condiciones y restricciones.',
	`VALOR_FINAL` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Valor correspondiente a la diferencia entre los datos de los campos VALOR_SERVICIO_REPUESTO y VALOR_DESCUENTO.',
	CONSTRAINT `PK_DETALLE_FACTURAS` PRIMARY KEY (`ID_DETALLE_FACTURA` ASC)
)
COMMENT = 'Tabla donde se almacena el detalle de los repuestos y servicios facturados.'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `DETALLE_FACTURAS` 
 ADD INDEX `IDX_ID_FACTURA` (`ID_FACTURA` ASC)
;

ALTER TABLE `DETALLE_FACTURAS` 
 ADD INDEX `IDX_ID_PRODUCTO` (`ID_PRODUCTO` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `DETALLE_FACTURAS` 
 ADD CONSTRAINT `FK_DETALLE_FACTURAS_FACTURAS`
	FOREIGN KEY (`ID_FACTURA`) REFERENCES `FACTURAS` (`ID_FACTURA`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `DETALLE_FACTURAS` 
 ADD CONSTRAINT `FK_DETALLE_FACTURAS_PRODUCTOS`
	FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTOS` (`ID_PRODUCTO`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
