/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 04-may.-2022 5:23:34 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `PERSONAS` CASCADE
;

/* Create Tables */

CREATE TABLE `PERSONAS`
(
	`ID_TIPO_DOCUMENTO` INT NOT NULL COMMENT 'Identificador del Tipo de Documento de la persona registrada. Hace parte de la llave primaria de la tabla. Es campo de llave foránea con la tabla TIPO_DOCUMENTO.',
	`NUMERO_DOCUMENTO` DECIMAL(15,0) NOT NULL COMMENT 'Número de identificación de la persona registrada. Hace parte de la llave primaria de la tabla.',
	`PRIMER_NOMBRE` NVARCHAR(30) NOT NULL COMMENT 'Primer nombre de la persona registrada.',
	`SEGUNDO_NOMBRE` NVARCHAR(30) NULL COMMENT 'Segundo nombre u otros nombres de la persona registrada.',
	`PRIMER_APELLIDO` NVARCHAR(30) NOT NULL COMMENT 'Primer apellido de la persona registrada.',
	`SEGUNDO_APELLIDO` NVARCHAR(30) NULL COMMENT 'Segundo apellido de la persona registrada.',
	`DIRECCION` NVARCHAR(100) NOT NULL COMMENT 'Dirección postal de la persona registrada.',
	`NUMERO_TELEFONO` NVARCHAR(20) NOT NULL COMMENT 'Número telefónico (fijo o celular) de la persona registrada.',
	`CORREO_ELECTRONICO` NVARCHAR(50) NOT NULL COMMENT 'Correo electrónico de contacto de la persona registrada.',
	`ESTADO` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Indicador de estado del registro de la persona. Puede ser ACTIVO (A), INACTIVO (I) o SUSPENDIDO (S).',
	`ID_TIPO_PERSONA` INT UNSIGNED NOT NULL COMMENT 'Código identificador del tipo de persona en este registro. Es campo de llave foránea con la tabla TIPOS_PERSONA.',
	CONSTRAINT `PK_PERSONA` PRIMARY KEY (`ID_TIPO_DOCUMENTO` ASC, `NUMERO_DOCUMENTO` ASC)
)
COMMENT = 'Tabla donde se almacenan los datos de las personas en el sistema.'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `PERSONAS` 
 ADD CONSTRAINT `CHECK_ESTADO` CHECK (ESTADO IN ('A','I','S'))
;

ALTER TABLE `PERSONAS` 
 ADD INDEX `IDX_TIPO_DOCUMENTO` (`ID_TIPO_DOCUMENTO` ASC)
;

ALTER TABLE `PERSONAS` 
 ADD INDEX `IDX_TIPO_PERSONA` (`ID_TIPO_PERSONA` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `PERSONAS` 
 ADD CONSTRAINT `FK_PERSONAS_TIPOS_DOCUMENTO`
	FOREIGN KEY (`ID_TIPO_DOCUMENTO`) REFERENCES `TIPOS_DOCUMENTO` (`ID_TIPO_DOCUMENTO`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `PERSONAS` 
 ADD CONSTRAINT `FK_PERSONAS_TIPOS_PERSONA`
	FOREIGN KEY (`ID_TIPO_PERSONA`) REFERENCES `TIPOS_PERSONA` (`ID_TIPO_PERSONA`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
