/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 04-may.-2022 5:22:45 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `TIPOS_PRODUCTO` CASCADE
;

/* Create Tables */

CREATE TABLE `TIPOS_PRODUCTO`
(
	`ID_TIPO_PRODUCTO` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Código identificador del tipo de producto. Es la llave primaria de la tabla.',
	`NOMBRE` NVARCHAR(30) NOT NULL COMMENT 'Denominación del tipo de producto.',
	`DESCRIPCION` NVARCHAR(100) NOT NULL COMMENT 'Descripción detallada del tipo de producto.',
	CONSTRAINT `PK_TIPOS_PRODUCTO` PRIMARY KEY (`ID_TIPO_PRODUCTO` ASC)
)
COMMENT = 'Tabla donde se almacenan los tipos de producto que se ofrecen en el almacén.'

;

SET FOREIGN_KEY_CHECKS=1
; 
