/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 04-may.-2022 5:22:19 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `TIPOS_DOCUMENTO` CASCADE
;

/* Create Tables */

CREATE TABLE `TIPOS_DOCUMENTO`
(
	`ID_TIPO_DOCUMENTO` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Código indentificador del tipo de documento de identificación. Es la llave primaria de la tabla.',
	`NOMBRE` NVARCHAR(30) NOT NULL COMMENT 'Denominación del tipo de documento de identificación.',
	`DESCRIPCION` NVARCHAR(100) NOT NULL COMMENT 'Descripción detallada del tipo de documento de identificación.',
	CONSTRAINT `PK_TIPOS_DOCUMENTO` PRIMARY KEY (`ID_TIPO_DOCUMENTO` ASC)
)
COMMENT = 'Tabla donde se almacenan los tipos de documento de identificación.'

;

SET FOREIGN_KEY_CHECKS=1
; 
