/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 05-may.-2022 4:46:32 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `FOTOS_VEHICULOS` CASCADE
;

/* Create Tables */

CREATE TABLE `FOTOS_VEHICULOS`
(
	`ID_FOTO_VEHICULO` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Código identificador de la fotografía del vehículo. Es la llave primaria de la tabla.',
	`MATRICULA_VEHICULO` NVARCHAR(10) NOT NULL COMMENT 'Placa o matrícula del vehículo que se ve en la foto. Es campo de llave foránea con la tabla VEHICULOS.',
	`FOTO` BLOB NULL COMMENT 'Fotografía del vehículo.',
	CONSTRAINT `PK_FOTOS_VEHICULOS` PRIMARY KEY (`ID_FOTO_VEHICULO` ASC)
)
COMMENT = 'Tabla que almacena fotos de los vehículos de los clientes para valoraciones iniciales.'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FOTOS_VEHICULOS` 
 ADD INDEX `IDX_MATRICULA_VEHICULO` (`MATRICULA_VEHICULO` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FOTOS_VEHICULOS` 
 ADD CONSTRAINT `FK_FOTOS_VEHICULOS_VEHICULOS`
	FOREIGN KEY (`MATRICULA_VEHICULO`) REFERENCES `VEHICULOS` (`MATRICULA`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
