/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 05-may.-2022 4:47:23 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `TIENDAS` CASCADE
;

/* Create Tables */

CREATE TABLE `TIENDAS`
(
	`ID_TIENDA` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Código identificador de la tienda. Es la llave primaria de la tabla.',
	`NOMBRE` NVARCHAR(50) NOT NULL COMMENT 'Nombre o razón social de la tienda.',
	`DIRECCION` NVARCHAR(50) NOT NULL COMMENT 'Dirección física de la tienda.',
	`TELEFONO` NVARCHAR(30) NOT NULL COMMENT 'Número (s) de teléfono (s) de contacto de la tienda.',
	CONSTRAINT `PK_TIENDAS` PRIMARY KEY (`ID_TIENDA` ASC)
)
COMMENT = 'Tabla que almacena el registro de las tiendas que ofrecen el servicio.'

;

SET FOREIGN_KEY_CHECKS=1
; 
