CREATE VIEW vista_mantenimientos_factura AS
    SELECT 
        MAN.ID_MANTENIMIENTO AS ID_MANTENIMIENTO,
        MAN.MATRICULA_VEHICULO AS MATRICULA_VEHICULO,
        TIC.ID_TIPO_DOCUMENTO AS ID_TIPO_DOCUMENTO_CLIENTE,
        TIC.NOMBRE AS TIPO_DOCUMENTO_CLIENTE,
        CLI.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO_CLIENTE,
        CLI.PRIMER_NOMBRE AS PRIMER_NOMBRE_CLIENTE,
        CLI.SEGUNDO_NOMBRE AS SEGUNDO_NOMBRE_CLIENTE,
        CLI.PRIMER_APELLIDO AS PRIMER_APELLIDO_CLIENTE,
        CLI.SEGUNDO_APELLIDO AS SEGUNDO_APELLIDO_CLIENTE,
        TIM.ID_TIPO_DOCUMENTO AS ID_TIPO_DOCUMENTO_MECANICO,
        TIM.NOMBRE AS TIPO_DOCUMENTO_MECANICO,
        MEC.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO_MECANICO,
        MEC.PRIMER_NOMBRE AS PRIMER_NOMBRE_MECANICO,
        MEC.SEGUNDO_NOMBRE AS SEGUNDO_NOMBRE_MECANICO,
        MEC.PRIMER_APELLIDO AS PRIMER_APELLIDO_MECANICO,
        MEC.SEGUNDO_APELLIDO AS SEGUNDO_APELLIDO_MECANICO,
        TIE.ID_TIENDA AS ID_TIENDA,
        TIE.NOMBRE AS NOMBRE_TIENDA,
        PRO.ID_PRODUCTO AS ID_PRODUCTO,
        PRO.DESCRIPCION AS DESCRIPCION,
        PRO.VALOR_UNITARIO_VENTA AS VALOR_UNITARIO_VENTA,
        DEM.CANTIDAD_UTILIZADA AS CANTIDAD_UTILIZADA,
        (DEM.CANTIDAD_UTILIZADA * PRO.VALOR_UNITARIO_VENTA) AS VALOR_PRODUCTO
    FROM
        MANTENIMIENTOS MAN
        ,DETALLE_MANTENIMIENTOS DEM
        ,VEHICULOS VEH
        ,PERSONAS CLI
        ,PERSONAS MEC
        ,PRODUCTOS PRO
        ,TIENDAS TIE
        ,TIPOS_DOCUMENTO TIC
        ,TIPOS_DOCUMENTO TIM
    WHERE
        MAN.ID_MANTENIMIENTO = DEM.ID_MANTENIMIENTO
        AND MAN.MATRICULA_VEHICULO = VEH.MATRICULA
        AND VEH.TIPO_DOCUMENTO_CLIENTE = CLI.ID_TIPO_DOCUMENTO
        AND VEH.NUMERO_DOCUMENTO_CLIENTE = CLI.NUMERO_DOCUMENTO
        AND MAN.TIPO_DOCUMENTO_MECANICO = MEC.ID_TIPO_DOCUMENTO
        AND MAN.NUMERO_DOCUMENTO_MECANICO = MEC.NUMERO_DOCUMENTO
        AND MAN.ID_TIENDA = TIE.ID_TIENDA
        AND DEM.ID_PRODUCTO = PRO.ID_PRODUCTO
        AND CLI.ID_TIPO_DOCUMENTO = TIC.ID_TIPO_DOCUMENTO
        AND MEC.ID_TIPO_DOCUMENTO = TIM.ID_TIPO_DOCUMENTO
        AND MAN.ESTADO = 'T'
        AND MAN.ID_FACTURA IS NULL;