/*Consulta de las tiendas que han vendido más de 100 unidadeds del producto 100 en los últimos 60 días*/
SELECT TIE.*
FROM DETALLE_MANTENIMIENTOS DEM
,MANTENIMIENTOS MAN
,VEHICULOS VEH
,PERSONAS PER
,TIENDAS TIE
WHERE MAN.ID_MANTENIMIENTO=DEM.ID_MANTENIMIENTO
AND MAN.MATRICULA_VEHICULO=VEH.MATRICULA
AND VEH.TIPO_DOCUMENTO_CLIENTE=PER.ID_TIPO_DOCUMENTO
AND VEH.NUMERO_DOCUMENTO_CLIENTE=PER.NUMERO_DOCUMENTO
AND TIE.ID_TIENDA=MAN.ID_TIENDA
AND MAN.ESTADO='T'
AND DEM.ID_PRODUCTO=100
AND MAN.FECHA_TERMINACION BETWEEN DATE_FORMAT(DATE_ADD(SYSDATE(),INTERVAL -60 DAY),'%Y-%m-%d') AND DATE_FORMAT(SYSDATE(),'%Y-%m-%d')
GROUP BY TIE.ID_TIENDA,DEM.ID_PRODUCTO
HAVING SUM(DEM.CANTIDAD_UTILIZADA)>100;