/*Consulta de clientes que han tenido más de un mantenimiento en los últimos 30 días*/
SELECT PER.*
FROM MANTENIMIENTOS MAN
,VEHICULOS VEH
,PERSONAS PER
WHERE MAN.MATRICULA_VEHICULO=VEH.MATRICULA
AND VEH.TIPO_DOCUMENTO_CLIENTE=PER.ID_TIPO_DOCUMENTO
AND VEH.NUMERO_DOCUMENTO_CLIENTE=PER.NUMERO_DOCUMENTO
AND MAN.ESTADO='T'
AND MAN.FECHA_TERMINACION BETWEEN DATE_FORMAT(DATE_ADD(SYSDATE(),INTERVAL -30 DAY),'%Y-%m-%d') AND DATE_FORMAT(SYSDATE(),'%Y-%m-%d')
GROUP BY PER.NUMERO_DOCUMENTO
HAVING COUNT(PER.NUMERO_DOCUMENTO)>1;