/*Consulta de los 100 productos más vendidos en los últimos 30 días*/
SELECT PROD.ID_PRODUCTO,PROD.DESCRIPCION,TP.NOMBRE AS TIPO_PRODUCTO 
FROM (
	SELECT DET.ID_PRODUCTO,SUM(VALOR_FINAL) AS TOTAL_PRODUCTO
	FROM DETALLE_FACTURAS DET
	,FACTURAS FAC
	WHERE DET.ID_FACTURA=FAC.ID_FACTURA
	AND FAC.FECHA_FACTURA BETWEEN DATE_FORMAT(DATE_ADD(SYSDATE(),INTERVAL -30 DAY),'%Y-%m-%d') AND DATE_FORMAT(SYSDATE(),'%Y-%m-%d')
	GROUP BY DET.ID_PRODUCTO
) VENTAS
, PRODUCTOS PROD
,TIPOS_PRODUCTO TP
WHERE PROD.ID_PRODUCTO=VENTAS.ID_PRODUCTO
AND PROD.ID_TIPO_PRODUCTO=TP.ID_TIPO_PRODUCTO
ORDER BY VENTAS.TOTAL_PRODUCTO DESC
LIMIT 100;