/*Consulta de clientes con compras acumuladas de $100.000 en los últimos 60 días*/

SELECT TD.NOMBRE AS TIPO_DOCUMENTO,PER.NUMERO_DOCUMENTO
,PER.PRIMER_APELLIDO,PER.SEGUNDO_APELLIDO,PER.PRIMER_NOMBRE,PER.SEGUNDO_NOMBRE
,PER.DIRECCION,PER.NUMERO_TELEFONO,PER.CORREO_ELECTRONICO
FROM (
	SELECT TIPO_DOCUMENTO_CLIENTE,NUMERO_DOCUMENTO_CLIENTE,TOTAL_FACTURA
	FROM FACTURAS
	WHERE FECHA_FACTURA BETWEEN DATE_FORMAT(DATE_ADD(SYSDATE(),INTERVAL -60 DAY),'%Y-%m-%d') AND DATE_FORMAT(SYSDATE(),'%Y-%m-%d')
	GROUP BY TIPO_DOCUMENTO_CLIENTE,NUMERO_DOCUMENTO_CLIENTE
	HAVING SUM(TOTAL_FACTURA)=100000
) FAC
,PERSONAS PER
,TIPOS_DOCUMENTO TD
WHERE FAC.TIPO_DOCUMENTO_CLIENTE=PER.ID_TIPO_DOCUMENTO
AND FAC.NUMERO_DOCUMENTO_CLIENTE=PER.NUMERO_DOCUMENTO
AND TD.ID_TIPO_DOCUMENTO=PER.ID_TIPO_DOCUMENTO;